# This file contains the default configuration for asphinx.
site = "."
no_default = false

[asciidoc]
extensions = ["asciidoctor-mathematical", "asciidoctor-diagram"]

[asciidoc.attributes]
icons = "font"
toc = 1
experimental = ""
source-highlighter = "pygments"
a2s-format = "svg"
actdiag-format = "svg"
blockdiag-format = "svg"
d2-format = "svg"
diagrams-format = "svg"
ditaa-format = "svg"
erd-format = "svg"
gnuplot-format = "svg"
graphviz-format = "svg"
mermaid-format = "svg"
mscgen-format = "svg"
nomnoml-format = "svg"
newdiag-format = "svg"
pintora-format = "svg"
plantuml-format = "svg"
seqdiag-format = "svg"
shappe-format = "svg"
smcat-format = "svg"
svgbob-format = "svg"
symbolator-format = "svg"
syntrax-format = "svg"
tikz-format = "svg"
umlet-format = "svg"
vega-format = "svg"
vegalite-format = "svg"
wavedrom-format = "svg"
