[package]
name = "asphinx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = { version = "1.10.2" }
rayon = "1.8.0"
minijinja = { version = '1.0.16', features = ["loader"] }
scraper = '0.19.0'
serde = { version = '1.0.197', features = ["derive"] }
futures = '0.3.30'
minify-html = '0.15.0'
clap = { version = '4.4.10', features = ["derive"] }
chrono = '0.4.37'
gix = '0.55.2'
log = '0.4.21'
tracing-subscriber = { version = "0.3.18", default_features = true, features = [
  "local-time",
  "time",
  "env-filter",
] }
mimalloc = { version = '0.1.39', default_features = false }
toml = "0.8.12"
lazy-regex = "3.1.0"
anyhow = "1.0.81"
time = { version = "0.3.30", features = ["macros"] }
tokio = { version = "1.37.0", features = ["full"] }
rust-embed = "8.0.0"
thiserror = "1.0.50"
