[package]
name = "asphinx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.13.0"
minijinja = { version = '2.3.1', features = ["loader"] }
scraper = '0.20.0'
serde = { version = '1.0.210', features = ["derive"] }
futures = '0.3.31'
minify-html = '0.15.0'
clap = { version = '4.5.20', features = ["derive"] }
chrono = '0.4.38'
gix = '0.66.0'
log = '0.4.22'
tracing-subscriber = { version = "0.3.18", default-features = true, features = [
  "local-time",
  "time",
  "env-filter",
] }
toml = "0.8.19"
lazy-regex = "3.3.0"
anyhow = "1.0.90"
time = { version = "0.3.36", features = ["macros"] }
tokio = { version = "1.40.0", features = [
  "fs",
  "process",
  "rt-multi-thread",
  "macros",
] }
rust-embed = "8.5.0"
thiserror = "1.0.64"
