[package]
name = "asphinx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = { version = "1.9.1" }
tokio = { version = "1.29.1", features = ["full"] }
minijinja = { version = '1.0.5', features = ["loader"] }
scraper = '0.17.1'
serde = { version = '1.0.171', features = ["derive"] }
futures = '0.3.28'
minify-html = '0.11.1'
clap = { version = '4.3.15', features = ["derive"] }
chrono = '0.4.26'
gix = '0.48'
log = '0.4.19'
env_logger = '0.10.0'
mimalloc = { version = '0.1.37', default_features = false }
