[package]
name = "asphinx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = { version = "1.8.4" }
tokio = { version = "1.28.2", features = ["full"] }
minijinja = { version = '1.0.0', features = ["loader"] }
scraper = '0.16.0'
serde = { version = '1.0.164', features = ["derive"] }
futures = '0.3.28'
minify-html = '0.11.1'
clap = { version = '4.3.4', features = ["derive"] }
chrono = '0.4.26'
gix = '0.46'
log = '0.4.19'
env_logger = '0.10.0'
mimalloc = { version = '0.1.37', default_features = false }
