[package]
name = "asphinx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = { version = "1.10.0" }
rayon = "1.8.0"
minijinja = { version = '1.0.8', features = ["loader"] }
scraper = '0.17.1'
serde = { version = '1.0.189', features = ["derive"] }
futures = '0.3.28'
minify-html = '0.11.1'
clap = { version = '4.4.6', features = ["derive"] }
chrono = '0.4.31'
gix = '0.55.2'
log = '0.4.20'
tracing-subscriber = { version = "0.3.17", default_features = true, features = [
  "local-time",
  "time",
  "env-filter",
] }
mimalloc = { version = '0.1.39', default_features = false }
toml = "0.8.2"
lazy-regex = "3.0.2"
anyhow = "1.0.75"
time = { version = "0.3.30", features = ["macros"] }
